---
 - name: Deploy to Tomcat
   hosts: web
   become: yes
   tasks:
    - name: Copy WAR file
      copy:
        src: "/var/snap/jenkins/"
        dest: "/opt/tomcat/webapps/My003.war"
        remote_src: no
        
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
